Repository oxxultus/lectureroom-reservation-server, pull requests merged in 2025-05, with the labels that each got.

#1 Guddnjs02
  src/main/java/deu/controller/ReservationController.java
  src/main/java/deu/model/dto/request/ReservationRequest.java
  src/main/java/deu/model/entity/Reservation.java
  src/main/java/deu/repository/ReservationRepository.java
  src/main/java/deu/service/ReservationService.java
Labels: documentation

#3 lgi0507
  src/main/java/deu/repository/UserRepositoryImpl.java
Labels: good first issue

#4 lgi0507
  src/main/java/deu/repository/UserRepositoryImpl.java
Labels: good first issue

#25 lgi0507
  src/main/java/deu/repository/UserRepositoryImpl.java
Labels: 개선 요청, 구현

#27 Guddnjs02
  .gitignore
  README.md
  pom.xml
  src/main/java/deu/ClientHandler.java
  src/main/java/deu/ServerMain.java
  src/main/java/deu/controller/LectureController.java
  src/main/java/deu/controller/ReservationController.java
  src/main/java/deu/controller/ReservationManagementController.java
  src/main/java/deu/controller/SystemController.java
  src/main/java/deu/controller/UserController.java
  src/main/java/deu/controller/UserManagementController.java
  src/main/java/deu/model/dto/request/command/LectureCommandRequest.java
  src/main/java/deu/model/dto/request/command/ReservationCommandRequest.java
  src/main/java/deu/model/dto/request/command/ReservationManagementCommandRequest.java
  src/main/java/deu/model/dto/request/command/UserCommandRequest.java
  src/main/java/deu/model/dto/request/command/UserManagementCommandRequest.java
  src/main/java/deu/model/dto/request/data/LoginRequest.java
  src/main/java/deu/model/dto/request/data/LogoutRequest.java
  src/main/java/deu/model/dto/request/data/SignupRequest.java
  src/main/java/deu/model/dto/response/BasicResponse.java
  src/main/java/deu/model/dto/response/CurrentResponse.java
  src/main/java/deu/model/entity/Lecture.java
  src/main/java/deu/model/entity/Reservation.java
  src/main/java/deu/model/entity/User.java
  src/main/java/deu/repository/ReservationRepository.java
  src/main/java/deu/repository/UserRepository.java
  src/main/java/deu/repository/UserRepositoryImpl.java
  src/main/java/deu/service/ReservationService.java
  src/main/java/deu/service/UserService.java
  src/test/java/deu/controller/SystemControllerTest.java
  src/test/java/deu/controller/UserControllerTest.java
  src/test/java/deu/repository/LectureRepositoryTest.java
  src/test/java/deu/repository/UserRepositoryTest.java
  src/test/java/deu/service/UserServiceTest.java
Labels: 도움 요청, good first issue
